/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/4-15': RouteRecordInfo<
      '/posts/4-15',
      '/posts/4-15',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/4-16': RouteRecordInfo<
      '/posts/4-16',
      '/posts/4-16',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/4-18': RouteRecordInfo<
      '/posts/4-18',
      '/posts/4-18',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/4-19': RouteRecordInfo<
      '/posts/4-19',
      '/posts/4-19',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/4-21': RouteRecordInfo<
      '/posts/4-21',
      '/posts/4-21',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/4-22': RouteRecordInfo<
      '/posts/4-22',
      '/posts/4-22',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/4-27': RouteRecordInfo<
      '/posts/4-27',
      '/posts/4-27',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/4-29': RouteRecordInfo<
      '/posts/4-29',
      '/posts/4-29',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/4-30': RouteRecordInfo<
      '/posts/4-30',
      '/posts/4-30',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-1': RouteRecordInfo<
      '/posts/5-1',
      '/posts/5-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-10': RouteRecordInfo<
      '/posts/5-10',
      '/posts/5-10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-11': RouteRecordInfo<
      '/posts/5-11',
      '/posts/5-11',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-12': RouteRecordInfo<
      '/posts/5-12',
      '/posts/5-12',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-13': RouteRecordInfo<
      '/posts/5-13',
      '/posts/5-13',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-16': RouteRecordInfo<
      '/posts/5-16',
      '/posts/5-16',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-17': RouteRecordInfo<
      '/posts/5-17',
      '/posts/5-17',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-2': RouteRecordInfo<
      '/posts/5-2',
      '/posts/5-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-3': RouteRecordInfo<
      '/posts/5-3',
      '/posts/5-3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-4': RouteRecordInfo<
      '/posts/5-4',
      '/posts/5-4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-5': RouteRecordInfo<
      '/posts/5-5',
      '/posts/5-5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-6': RouteRecordInfo<
      '/posts/5-6',
      '/posts/5-6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-7': RouteRecordInfo<
      '/posts/5-7',
      '/posts/5-7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-8': RouteRecordInfo<
      '/posts/5-8',
      '/posts/5-8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/5-9': RouteRecordInfo<
      '/posts/5-9',
      '/posts/5-9',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/April.plan': RouteRecordInfo<
      '/posts/April.plan',
      '/posts/April/plan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/May.plan': RouteRecordInfo<
      '/posts/May.plan',
      '/posts/May/plan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.5_magicast@0.5.2_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.5_@babel+parser@7.29.2_@nuxt+kit@3.21.2_magicast@0.5.2__@types+markdown-it@_8273e637c83a25366da28a2f954a4011/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.5_magicast@0.5.2_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.5_magicast@0.5.2_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/4-15.md': {
      routes:
        | '/posts/4-15'
      views:
        | never
    }
    'pages/posts/4-16.md': {
      routes:
        | '/posts/4-16'
      views:
        | never
    }
    'pages/posts/4-18.md': {
      routes:
        | '/posts/4-18'
      views:
        | never
    }
    'pages/posts/4-19.md': {
      routes:
        | '/posts/4-19'
      views:
        | never
    }
    'pages/posts/4-21.md': {
      routes:
        | '/posts/4-21'
      views:
        | never
    }
    'pages/posts/4-22.md': {
      routes:
        | '/posts/4-22'
      views:
        | never
    }
    'pages/posts/4-27.md': {
      routes:
        | '/posts/4-27'
      views:
        | never
    }
    'pages/posts/4-29.md': {
      routes:
        | '/posts/4-29'
      views:
        | never
    }
    'pages/posts/4-30.md': {
      routes:
        | '/posts/4-30'
      views:
        | never
    }
    'pages/posts/5-1.md': {
      routes:
        | '/posts/5-1'
      views:
        | never
    }
    'pages/posts/5-10.md': {
      routes:
        | '/posts/5-10'
      views:
        | never
    }
    'pages/posts/5-11.md': {
      routes:
        | '/posts/5-11'
      views:
        | never
    }
    'pages/posts/5-12.md': {
      routes:
        | '/posts/5-12'
      views:
        | never
    }
    'pages/posts/5-13.md': {
      routes:
        | '/posts/5-13'
      views:
        | never
    }
    'pages/posts/5-16.md': {
      routes:
        | '/posts/5-16'
      views:
        | never
    }
    'pages/posts/5-17.md': {
      routes:
        | '/posts/5-17'
      views:
        | never
    }
    'pages/posts/5-2.md': {
      routes:
        | '/posts/5-2'
      views:
        | never
    }
    'pages/posts/5-3.md': {
      routes:
        | '/posts/5-3'
      views:
        | never
    }
    'pages/posts/5-4.md': {
      routes:
        | '/posts/5-4'
      views:
        | never
    }
    'pages/posts/5-5.md': {
      routes:
        | '/posts/5-5'
      views:
        | never
    }
    'pages/posts/5-6.md': {
      routes:
        | '/posts/5-6'
      views:
        | never
    }
    'pages/posts/5-7.md': {
      routes:
        | '/posts/5-7'
      views:
        | never
    }
    'pages/posts/5-8.md': {
      routes:
        | '/posts/5-8'
      views:
        | never
    }
    'pages/posts/5-9.md': {
      routes:
        | '/posts/5-9'
      views:
        | never
    }
    'pages/posts/April.plan.md': {
      routes:
        | '/posts/April.plan'
      views:
        | never
    }
    'pages/posts/May.plan.md': {
      routes:
        | '/posts/May.plan'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
